// src/abi/ritualArena.ts
// RitualArena V5 — battle system. AP-backed community voting,
// power-handicap weighted, no ELO, no daily check-in.

export const ritualArenaAbi = [
  // Errors
  { type: "error", name: "NotEligible", inputs: [{ type: "string", name: "reason" }] },
  { type: "error", name: "NoAnthem", inputs: [] },
  { type: "error", name: "AlreadyInBattle", inputs: [] },
  { type: "error", name: "Cooldown", inputs: [] },
  { type: "error", name: "BadInput", inputs: [] },
  { type: "error", name: "BattleNotFound", inputs: [] },
  { type: "error", name: "NotSettled", inputs: [] },
  { type: "error", name: "NotSettledYet", inputs: [] },
  { type: "error", name: "BattleNotEnded", inputs: [] },
  { type: "error", name: "NotParticipant", inputs: [] },
  { type: "error", name: "SameSideOnly", inputs: [] },
  { type: "error", name: "InsufficientAP", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "NotKeeper", inputs: [] },
  { type: "error", name: "PowerDeltaTooLarge", inputs: [] },
  // Constants
  { type: "function", name: "BATTLE_DURATION", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "COOLDOWN", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "REPEAT_COOLDOWN", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "CYCLE_INTERVAL", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "MAX_BATTLES_PER_CYCLE", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "MAX_POWER_DELTA", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "HANDICAP_DIV", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "MAX_HANDICAP_BPS", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "FEE_BPS", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "MAX_ARENA_SCORE", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "LB_SIZE", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  // External refs
  { type: "function", name: "ap", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "identityRegistry", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "identityCard", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  // Matchmaker state
  { type: "function", name: "keeper", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "lastCycletime", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lastBattleEndTime", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "arenaOptOut", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "lastOpponentMatch", stateMutability: "view", inputs: [{ type: "address" }, { type: "address" }], outputs: [{ type: "uint256" }] },
  // Battle state
  { type: "function", name: "nextBattleId", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "battles", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [
    { type: "tuple", components: [
      { type: "address", name: "walletA" },
      { type: "address", name: "walletB" },
      { type: "uint256", name: "startTime" },
      { type: "uint256", name: "endTime" },
      { type: "bool", name: "settled" },
      { type: "uint8", name: "outcome" },
      { type: "uint256", name: "votedApPoolA" },
      { type: "uint256", name: "votedApPoolB" },
      { type: "uint256", name: "powerA" },
      { type: "uint256", name: "powerB" },
    ]}
  ] },
  { type: "function", name: "activeBattleOf", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "voterSide", stateMutability: "view", inputs: [{ type: "uint256" }, { type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "voterSideSet", stateMutability: "view", inputs: [{ type: "uint256" }, { type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "userStakeA", stateMutability: "view", inputs: [{ type: "uint256" }, { type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "userStakeB", stateMutability: "view", inputs: [{ type: "uint256" }, { type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "votedApPoolClaimable", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint256" }] },
  // Player stats
  { type: "function", name: "arenaStats", stateMutability: "view", inputs: [{ type: "address" }], outputs: [
    { type: "uint256", name: "wins" },
    { type: "uint256", name: "losses" },
    { type: "uint256", name: "settledBattles" },
    { type: "uint256", name: "supportGiven" },
    { type: "uint256", name: "supportReceived" },
    { type: "uint256", name: "arenaScore" },
    { type: "uint256", name: "winStreak" },
    { type: "uint256", name: "bestWinStreak" },
  ] },
  { type: "function", name: "leaderboardIndex", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "leaderboard", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "address" }] },
  { type: "function", name: "historyCount", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256" }] },
  // Setters
  { type: "function", name: "setAP", stateMutability: "nonpayable", inputs: [{ type: "address" }], outputs: [] },
  { type: "function", name: "setIdentityRegistry", stateMutability: "nonpayable", inputs: [{ type: "address" }], outputs: [] },
  { type: "function", name: "setIdentityCard", stateMutability: "nonpayable", inputs: [{ type: "address" }], outputs: [] },
  { type: "function", name: "setKeeper", stateMutability: "nonpayable", inputs: [{ type: "address" }], outputs: [] },
  { type: "function", name: "setArenaOptOut", stateMutability: "nonpayable", inputs: [{ type: "bool" }], outputs: [] },
  { type: "function", name: "pause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "unpause", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "renounceOwnership", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "transferOwnership", stateMutability: "nonpayable", inputs: [{ type: "address" }], outputs: [] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  // Battle actions
  { type: "function", name: "createBattle", stateMutability: "nonpayable", inputs: [{ type: "address" }, { type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "scheduleBatch", stateMutability: "nonpayable", inputs: [{ type: "tuple[2][]" }], outputs: [] },
  { type: "function", name: "voteAP", stateMutability: "nonpayable", inputs: [{ type: "uint256" }, { type: "bool" }, { type: "uint256" }], outputs: [] },
  { type: "function", name: "settle", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  { type: "function", name: "claimVotedAP", stateMutability: "nonpayable", inputs: [{ type: "uint256" }], outputs: [] },
  // Views
  { type: "function", name: "isMatchmakingEligible", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "bool" }, { type: "string" }] },
  { type: "function", name: "timeLeft", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "effectiveWeights", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [{ type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }] },
  { type: "function", name: "getArenaStats", stateMutability: "view", inputs: [{ type: "address" }], outputs: [
    { type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" },
    { type: "uint256" }, { type: "uint256" }, { type: "uint256" }, { type: "uint256" }
  ] },
  { type: "function", name: "getRecentBattles", stateMutability: "view", inputs: [{ type: "address" }], outputs: [{ type: "uint256[]" }] },
  { type: "function", name: "getLeaderboard", stateMutability: "view", inputs: [{ type: "uint256" }, { type: "uint256" }], outputs: [{ type: "address[]" }, { type: "uint256[]" }] },
  { type: "function", name: "leaderboardLength", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "getBattle", stateMutability: "view", inputs: [{ type: "uint256" }], outputs: [
    { type: "address", name: "walletA" },
    { type: "address", name: "walletB" },
    { type: "uint256", name: "startTime" },
    { type: "uint256", name: "endTime" },
    { type: "bool", name: "settled" },
    { type: "uint8", name: "outcome" },
    { type: "uint256", name: "votedApPoolA" },
    { type: "uint256", name: "votedApPoolB" },
    { type: "uint256", name: "powerA" },
    { type: "uint256", name: "powerB" },
  ] },
  // Events
  { type: "event", name: "BattleCreated", inputs: [
    { type: "uint256", indexed: true, name: "id" },
    { type: "address", indexed: true, name: "a" },
    { type: "address", indexed: true, name: "b" },
    { type: "uint256", name: "end" },
  ] },
  { type: "event", name: "VotedAP", inputs: [
    { type: "uint256", indexed: true, name: "id" },
    { type: "address", indexed: "voter" },
    { type: "bool", name: "forA" },
    { type: "uint256", name: "amount" },
  ] },
  { type: "event", name: "BattleSettled", inputs: [
    { type: "uint256", indexed: true, name: "id" },
    { type: "address", indexed: "winner" },
    { type: "uint256", name: "poolA" },
    { type: "uint256", name: "poolB" },
    { type: "uint256", name: "powerA" },
    { type: "uint256", name: "powerB" },
  ] },
  { type: "event", name: "VotedAPClaimed", inputs: [
    { type: "uint256", indexed: true, name: "id" },
    { type: "address", indexed: true, name: "backer" },
    { type: "uint256", name: "amount" },
  ] },
  { type: "event", name: "MatchmakingCycleComplete", inputs: [
    { type: "uint256", name: "t" }, { type: "uint256", name: "c" }, { type: "uint256", name: "s" },
  ] },
  { type: "event", name: "ArenaOptOut", inputs: [
    { type: "address", indexed: true, name: "w" }, { type: "bool", name: "o" },
  ] },
  { type: "event", name: "KeeperSet", inputs: [
    { type: "address", indexed: true, name: "k" },
  ] },
  { type: "event", name: "ArenaScoreUpdated", inputs: [
    { type: "address", indexed: true, name: "w" },
    { type: "uint256", name: "newScore" },
    { type: "uint256", name: "delta" },
  ] },
  { type: "event", name: "BattleStatsUpdated", inputs: [
    { type: "address", indexed: true, name: "w" },
    { type: "uint256", name: "wins" },
    { type: "uint256", name: "losses" },
    { type: "uint256", name: "settledBattles" },
  ] },
  { type: "event", name: "APAddressUpdated", inputs: [{ type: "address", indexed: true, name: "ap" }] },
  { type: "event", name: "IdentityRegistryUpdated", inputs: [{ type: "address", indexed: true, name: "registry" }] },
  { type: "event", name: "IdentityCardUpdated", inputs: [{ type: "address", indexed: true, name: "card" }] },
] as const;
